server:
  port: 8888
spring:
  application:
    name: config-server
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/Mark/IdeaProjects/securities-exchange/config/config-files
