server:
  port: 0

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres

  application:
    name: paying-service
  rabbitmq:
    host: localhost
    port: 5672
    username: rm
    password: rmp
  cloud:
    stream:
      bindings:
        paymentProofEventProcessor-out-0:
          destination: payment-proof


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

springdoc:
  swagger-ui:
    configUrl: /paying-service/v3/api-docs/swagger-config
    url: /paying-service/v3/api-docs
    api-docs:
      enabled: true