server:
  port: 0

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

springdoc:
  swagger-ui:
    configUrl: /paying-service/v3/api-docs/swagger-config
    url: /paying-service/v3/api-docs
    api-docs:
      enabled: true