server:
  port: 0

spring:
  datasource:
    username: postgres
    password: postgres
    uri: jdbc:postgresql://localhost:5432/postgres

    #Перекомпилировать конфиг файлы а не только  paying-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
