spring:
  datasource:
    username: postgres
    password: postgrespw
    url: jdbc:postgresql://host.docker.internal:49153/postgres
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30