spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
      preferIpAddress: true
      lease-renewal-interval-in-seconds: 30
alpha-vantage:
  api:
    url: https://www.alphavantage.co/query/?function=%s&symbol=%s&apikey=%s
    key: R5Y1MX285BT0WOJZ
    global-function: GLOBAL_QUOTE
    overview-function: OVERVIEW
webclient:
  timeout: 10000
tinkoff:
  api:
    token: t.qkfYsq60_C584svox3zRIqfXVMp7emIdZLYMTJIc2dHfr7Jtssh9pJ-WjJiO98IUPJTYWThbIUWb37SrGTMiNg
    sandbox: t.OlKXgNUlgSJ9X1JGcJ8J_ABQcVhJJ6wdMYTZB6Owyx0zqA5i1MoWPcm-3b1ma_XrZtj5OooL7AI2GEQXZgZeMg
    is-sandbox-mode: true