spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
      preferIpAddress: true
      lease-renewal-interval-in-seconds: 30
alpha-vantage:
  api:
    url: https://www.alphavantage.co/query/?function=%s&symbol=%s&apikey=%s
    key: R5Y1MX285BT0WOJZ
    global-function: GLOBAL_QUOTE
    overview-function: OVERVIEW
webclient:
  timeout: 10000